import React from 'react';
import { useIntl } from 'react-intl';

type BairroRegiaoValue = {
  regiao: string;
  bairro: string;
};

type InputProps = {
  attribute: { type: string };
  disabled?: boolean;
  intlLabel: { id: string; defaultMessage: string };
  name: string;
  onChange: (event: { target: { name: string; type: string; value: BairroRegiaoValue } }) => void;
  required?: boolean;
  value?: BairroRegiaoValue | string | null;
};

const todosBairros: string[] = [
  "Aero Rancho",
  "Altos da Afonso Pena",
  "Amambaí",
  "Amantini Residence",
  "Anhanduí",
  "Arapongas",
  "Arnaldo Estevão de Figueiredo",
  "Atlântico Sul",
  "Autonomista",
  "Beirute Residence Park",
  "Bela Laguna",
  "Bom Retiro",
  "Bosque das Araras",
  "Bosque de Avilan",
  "Bosque Santa Mônica",
  "Bosque Santa Mônica II",
  "Buriti",
  "Cabreúva",
  "Cachoeirinha",
  "Caiçara",
  "Carandá",
  "Carandá Bosque I",
  "Carandá Bosque II",
  "Carandá Bosque III",
  "Cascudo",
  "Centenário",
  "Center Park",
  "Centro",
  "Chácara Boa Vista",
  "Chácara Cachoeira",
  "Chácara Cachoeira II",
  "Chácara das Mansões",
  "Chácara dos Coqueiros",
  "Chácara dos Poderes",
  "Chácara José Antônio Pereira",
  "Chácara Vendas",
  "Cidade Jardim",
  "Clube Campestre Ypê",
  "Cofermat",
  "Cohafama",
  "Condominio Fernando Sabino",
  "Conjunto Hab. Jardim Anápolis",
  "Conjunto Hab. Jardim Roselândia",
  "Conjunto Oscar Salazar",
  "Conjunto Res. Leon Denizart Conte",
  "Conjunto Res. Monte Castelo",
  "Conjunto Res. Nova Bahia",
  "Conjunto Res. Nova Olinda",
  "Conjunto Res. Novo Alagoas",
  "Conjunto Res. Novo Amazonas",
  "Conjunto Res. Novo Maranhão",
  "Conjunto Res. Novo Minas Gerais",
  "Conjunto Res. Novo Paraná",
  "Conjunto Res. Novo Pernambuco",
  "Conjunto Res. Novo Rio Grande do Sul",
  "Conjunto Res. Novo São Paulo",
  "Conjunto Res. Novo Sergipe",
  "Conjunto União",
  "Coophaban",
  "Coophafé",
  "Coophagrande",
  "Coophamat",
  "Coophamorena",
  "Coopharádio",
  "Coophasul",
  "Coophatrabalho",
  "Coophavila",
  "Coophavila II",
  "Coronel Antonino",
  "Costa Verde",
  "Cruzeiro",
  "Desbarrancado",
  "Desm. Esteban Cornelas",
  "Eldorado",
  "Enseada dos Pássaros",
  "Estrela do Sul",
  "Estrela Park",
  "Flamboyant",
  "Giocondo Orsi",
  "Giocondo Orsi II",
  "Golden Gate Park",
  "Granja Bandeira",
  "Granja São Luiz",
  "Guanabara",
  "Guanandi",
  "Indubrasil",
  "Industrial",
  "Iracy Coelho",
  "Itamarati",
  "Itanhangá Park",
  "Jacy",
  "Jardim 7 de Setembro",
  "Jardim Aclimação",
  "Jardim Aeroporto",
  "Jardim Águas Vivas",
  "Jardim Agulhas Negras",
  "Jardim Alegre",
  "Jardim Alto São Francisco",
  "Jardim Alvorada",
  "Jardim América",
  "Jardim Ametista",
  "Jardim Anache",
  "Jardim Anhanguera",
  "Jardim Antáres",
  "Jardim Antartica",
  "Jardim Arco Iris",
  "Jardim Aroeira",
  "Jardim Autonomista",
  "Jardim Autonomista II",
  "Jardim Autonomista III",
  "Jardim Auxiliadora",
  "Jardim Bálsamo",
  "Jardim Barcelona",
  "Jardim Batistão",
  "Jardim Bela Vista",
  "Jardim Bonança",
  "Jardim Botafogo",
  "Jardim Botânico",
  "Jardim Botânico II",
  "Jardim Brasil",
  "Jardim Cabral",
  "Jardim Campina Verde",
  "Jardim Campo Alto",
  "Jardim Campo Belo",
  "Jardim Campo Nobre",
  "Jardim Campo Novo",
  "Jardim Canadá",
  "Jardim Canguru",
  "Jardim Carioca",
  "Jardim Centenário",
  "Jardim Centro Oeste",
  "Jardim Cidade",
  "Jardim Cidade Morena",
  "Jardim Colibri",
  "Jardim Colibri II",
  "Jardim Colonial",
  "Jardim Colorado",
  "Jardim Columbia",
  "Jardim Corcovado",
  "Jardim Cristo Redentor",
  "Jardim da Mooca",
  "Jardim das Acácias",
  "Jardim das Cássias",
  "Jardim das Cerejeiras",
  "Jardim das Hortências I",
  "Jardim das Hortências II",
  "Jardim das Hortências III",
  "Jardim das Macaúbas",
  "Jardim das Mansões Universitárias",
  "Jardim das Meninas",
  "Jardim das Nações",
  "Jardim das Paineiras",
  "Jardim das Perdizes",
  "Jardim das Reginas",
  "Jardim das Virtudes",
  "Jardim de Allah",
  "Jardim do Córrego",
  "Jardim dos Boggi",
  "Jardim dos Estados",
  "Jardim Estrela Dalva I",
  "Jardim Estrela Dalva II",
  "Jardim Estrela Dalva III",
  "Jardim Fluminense",
  "Jardim Guarujá",
  "Jardim Ibirapuera",
  "Jardim Imá",
  "Jardim Imperial",
  "Jardim Inápolis",
  "Jardim Indianápolis",
  "Jardim Ipanema",
  "Jardim Itália",
  "Jardim Itamaracá",
  "Jardim Itapema",
  "Jardim Itatiaia",
  "Jardim Jacarandá",
  "Jardim Jacy",
  "Jardim Jane",
  "Jardim Jerusalém",
  "Jardim Jockey Club",
  "Jardim Lagoa Dourada",
  "Jardim Leblon",
  "Jardim Leonidia",
  "Jardim Los Angeles",
  "Jardim Macapá",
  "Jardim Manaíra",
  "Jardim Mansur",
  "Jardim Marabá",
  "Jardim Marajoara",
  "Jardim Mathilde",
  "Jardim Mato Grosso",
  "Jardim Mirasol",
  "Jardim Moema",
  "Jardim Monte Alegre",
  "Jardim Monte Alto",
  "Jardim Monte Líbano",
  "Jardim Monte Verde",
  "Jardim Monterey",
  "Jardim Montevidéu",
  "Jardim Monumento",
  "Jardim Morenão",
  "Jardim N. Sra. do Perpétuo Socorro",
  "Jardim Nascente do Segredo",
  "Jardim Nashiville",
  "Jardim Nhanhá",
  "Jardim Noroeste",
  "Jardim Nova Era",
  "Jardim Nova Jerusalém",
  "Jardim Oracilia",
  "Jardim Ouro Preto",
  "Jardim Ouro Verde",
  "Jardim Pacaembu",
  "Jardim Panamá",
  "Jardim Paradiso",
  "Jardim Parati",
  "Jardim Parati II",
  "Jardim Paris",
  "Jardim Paulista",
  "Jardim Paulo Coelho Machado",
  "Jardim Pênfigo",
  "Jardim Petrópolis",
  "Jardim Pinheiros",
  "Jardim Piracicaba",
  "Jardim Presidente",
  "Jardim Radialista",
  "Jardim Roselândia",
  "Jardim Rubiácea",
  "Jardim Samambaia",
  "Jardim Santa Catarina",
  "Jardim Santa Emília",
  "Jardim Santa Felicidade",
  "Jardim Santa Úrsula",
  "Jardim São Bento",
  "Jardim São Conrado",
  "Jardim São Lourenço",
  "Jardim São Paulo",
  "Jardim Sayonara",
  "Jardim Seminário",
  "Jardim Serra Azul",
  "Jardim Sumatra",
  "Jardim Talismã",
  "Jardim Tarumã",
  "Jardim Tijuca I",
  "Jardim Tijuca II",
  "Jardim Tropical",
  "Jardim TV Morena",
  "Jardim Uirapuru",
  "Jardim Umuarama",
  "Jardim Veneza",
  "Jardim Veraneio",
  "Jardim Vicentino",
  "Jardim Vida Nova",
  "Jardim Vila Kellen",
  "Jardim Villas Lobos",
  "Jardim Villas Lobos II",
  "Jardim Vista Alegre",
  "Jardim Vitória",
  "Jardim Vitrine",
  "Jardim Zé Pereira",
  "Jatiúca Park",
  "Joana Darc",
  "José Abrão",
  "José Tavares do Couto",
  "Lageado",
  "Lagoa da Cruz",
  "Lagoa Park",
  "Lar do Trabalhador",
  "Lot. Mul. Dom Antonio Barbosa",
  "Lot. Municipal Alan Soares",
  "Lot. Municipal Dalva de Oliveira",
  "Loteamento Abaeté",
  "Loteamento Aero Rancho",
  "Loteamento Água Limpa Park",
  "Loteamento Alto da Boa Vista",
  "Loteamento Bonjardim",
  "Loteamento Bosque da Esperança",
  "Loteamento Guanandi II",
  "Loteamento José Maksoud",
  "Loteamento Nova Serrana",
  "Loteamento Paraíso do Lageado",
  "Loteamento Paulo VI",
  "Loteamento Porto Seguro",
  "Loteamento Portobello",
  "Loteamento Praia da Urca",
  "Loteamento Rancho Alegre I",
  "Loteamento Rancho Alegre II",
  "Loteamento Rancho Alegre IV",
  "Loteamento Reserva Santa Inês",
  "Loteamento Sóter",
  "Loteamento Tarsila do Amaral",
  "Loteamento Treviso",
  "Loteamento Vida Nova III",
  "Maria Aparecida Pedrossian",
  "Mata do Jacinto",
  "Mata do Segredo",
  "Monte Carlo",
  "Monte Castelo",
  "Monte Verde",
  "Montevidéu",
  "Morada do Sol",
  "Morada do Sossego",
  "Morada do Sossego II",
  "Morada dos Deuses",
  "Morada Imperial",
  "Morada Verde",
  "Moreninha",
  "N. Sra. das Graças",
  "N. Sra. de Fátima",
  "Nasa Park",
  "North Park",
  "Nova Campo Grande",
  "Nova Capital",
  "Nova Jeruzalém",
  "Nova Lima",
  "Novos Estados",
  "Núcleo Aero Rancho",
  "Núcleo Aero Rancho I",
  "Núcleo Alves Pereira",
  "Núcleo Colibri II",
  "Núcleo Habitacional Aero Rancho",
  "Núcleo Habitacional Aero Rancho I",
  "Núcleo Habitacional Aero Rancho II",
  "Núcleo Habitacional Aero Rancho III",
  "Núcleo Habitacional Aero Rancho IV",
  "Núcleo Habitacional Aero Rancho V",
  "Núcleo Habitacional Universitárias",
  "Núcleo Habitacional Universitárias I",
  "Núcleo Habitacional Universitárias II",
  "Núcleo Industrial",
  "Panamá III",
  "Panorama",
  "Parati",
  "Parque Atlântico",
  "Parque Dallas",
  "Parque do Lageado",
  "Parque do Sol",
  "Parque do Trabalhador",
  "Parque dos Ipês",
  "Parque dos Laranjais",
  "Parque dos Poderes",
  "Parque dos Sabiás",
  "Parque Iguatemi",
  "Parque Isabel Gardens",
  "Parque Novo Século",
  "Parque Residencial dos Bancários",
  "Parque Rita Vieira",
  "Petrópoles",
  "Pioneiros",
  "Popular",
  "Portal Caiobá",
  "Portal Caiobá II",
  "Portal do Gramado",
  "Portal do Panamá",
  "Portinho Pache",
  "Porto Belo",
  "Porto Galo",
  "Pq. Res. Maria Aparecida Pedrossian",
  "Pq. Residencial Azaléia",
  "Pq. Residencial Bellinate",
  "Pq. Residencial Damha I",
  "Pq. Residencial Damha II",
  "Pq. Residencial Damha III",
  "Pq. Residencial Damha IV",
  "Pq. Residencial dos Girassóis",
  "Pq. Residencial Lisboa",
  "Pq. Residencial União",
  "Pq. Residencial União II",
  "Recanto das Andorinhas",
  "Recanto das Paineiras",
  "Recanto do Cerrado",
  "Recanto dos Pássaros",
  "Recanto dos Rouxinóis",
  "Recanto Pantaneiro",
  "Regina",
  "Residencial Alphaville",
  "Residencial Alphaville II",
  "Residencial Alphaville III",
  "Residencial Alphaville IV",
  "Residencial Alto Tamandaré",
  "Residencial Ana Maria do Couto",
  "Residencial Aquarius I",
  "Residencial Aquarius II",
  "Residencial Betaville",
  "Residencial Botafogo",
  "Residencial Búzios",
  "Residencial Carajás",
  "Residencial Colonial",
  "Residencial Delfos",
  "Residencial do Lago",
  "Residencial Eucaliptos",
  "Residencial Figueiras do Parque",
  "Residencial Flores",
  "Residencial Gama",
  "Residencial Ilhéus",
  "Residencial João Scarano",
  "Residencial Madri",
  "Residencial Mário Cóvas",
  "Residencial Nova Tiradentes",
  "Residencial Oiti",
  "Residencial Oliveira I",
  "Residencial Oliveira II",
  "Residencial Oliveira III",
  "Residencial Otávio Pécora",
  "Residencial Praia da Enseada",
  "Residencial Ramez Tebet",
  "Residencial Rancharia",
  "Residencial Sagarana",
  "Residencial Santa Celina",
  "Residencial Shalom",
  "Residencial Sírio Libanês I",
  "Residencial Sírio Libanês II",
  "Residencial Tolentino",
  "Residencial Via Park Itália",
  "Residencial Vila Olimpica",
  "Residencial Village",
  "Rita Vieira",
  "Riviera Home Club",
  "Riviera Park",
  "Rouxinóis",
  "Royal Park",
  "Santa Carmélia",
  "Santa Fé",
  "Santo Amaro",
  "Santo Antônio",
  "Santos Dumont",
  "São Caetano",
  "São Francisco",
  "São Pedro",
  "Seminário",
  "Serraville",
  "Setvillage I",
  "Setvillage II",
  "Silvia Regina",
  "Sitio Santa Maria",
  "Sitiocas Alvorada",
  "Sky Residence",
  "Taquaral Bosque",
  "Taquarussú",
  "Tayamã Park",
  "Terras Alpha",
  "Terras do Golfe",
  "Tijuca",
  "Tiradentes",
  "União",
  "Universitário",
  "Universitário Seção B",
  "Universitário Seção D",
  "Vespasiano Martins",
  "Vila Abdalla",
  "Vila Abdo",
  "Vila Adelina",
  "Vila Aimoré",
  "Vila Aimoré II",
  "Vila Alba",
  "Vila Albuquerque",
  "Vila Almeida",
  "Vila Almeida Lima",
  "Vila Alta",
  "Vila Alto Campo de Marte",
  "Vila Alto das Paineiras",
  "Vila Alto Sumaré",
  "Vila Alves Pereira",
  "Vila Amapá",
  "Vila América",
  "Vila Americana",
  "Vila Anahy",
  "Vila Anfe",
  "Vila Antonieta",
  "Vila Antonio Inácio de Souza",
  "Vila Antônio Vendas",
  "Vila Antunes",
  "Vila Aprazível",
  "Vila Aurora",
  "Vila Bandeirante",
  "Vila Barão do Rio Branco",
  "Vila Bartiria",
  "Vila Bela",
  "Vila Belo Horizonte",
  "Vila Benjamim",
  "Vila Bernardo Goldman",
  "Vila Boa Vista",
  "Vila Bom Jardim",
  "Vila Bom Jesus",
  "Vila Bosque da Saudade",
  "Vila Capri",
  "Vila Carlota",
  "Vila Carolina",
  "Vila Carvalho",
  "Vila Carvalho Baís",
  "Vila Castelo",
  "Vila Catarina",
  "Vila Catarina II",
  "Vila Célia",
  "Vila Cidade Morena",
  "Vila Clélia",
  "Vila Clementina",
  "Vila Concórdia",
  "Vila Corumbá",
  "Vila Costa Lima",
  "Vila Coutinho",
  "Vila Cristina",
  "Vila da Saúde",
  "Vila Dalila",
  "Vila Danúbio Azul",
  "Vila do Polonês",
  "Vila Dom Pedrito",
  "Vila dos Ferroviários",
  "Vila Dr. João Rosa",
  "Vila Duque de Caxias",
  "Vila Eliane",
  "Vila Entroncamento",
  "Vila Espanhola",
  "Vila Esplanada",
  "Vila Esportiva",
  "Vila Estephania",
  "Vila Eva",
  "Vila Feliciana Carolina",
  "Vila Fernanda",
  "Vila Floresta",
  "Vila Flório",
  "Vila Fortuna",
  "Vila Futurista",
  "Vila Galvão",
  "Vila Gaspar",
  "Vila Gatão",
  "Vila General Wolgrand",
  "Vila Glória",
  "Vila Gomes",
  "Vila Guaraciaba",
  "Vila Guarani",
  "Vila Guenka",
  "Vila Helena",
  "Vila Ieda",
  "Vila Ilgenfritz",
  "Vila Independência",
  "Vila Ipiranga",
  "Vila Isis",
  "Vila Jardim Beija-Flor",
  "Vila Jardim Pioneiros",
  "Vila Jardim São Bernardo",
  "Vila Joselito",
  "Vila Julieta",
  "Vila Jurema",
  "Vila Jussara",
  "Vila Leda",
  "Vila Lia",
  "Vila Liberdade",
  "Vila Lídia",
  "Vila Lucinda",
  "Vila Maciel",
  "Vila Mandeta",
  "Vila Manoel da Costa Lima",
  "Vila Manoel Taveira",
  "Vila Maracajú",
  "Vila Marcos Roberto",
  "Vila Margarida",
  "Vila Maria",
  "Vila Mariana",
  "Vila Marisa",
  "Vila Marli",
  "Vila Marman",
  "Vila Miguel Couto",
  "Vila Moreninha I",
  "Vila Moreninha II",
  "Vila Moreninha III",
  "Vila Moreninha IV",
  "Vila Morumbi",
  "Vila N. Sra. Aparecida",
  "Vila N. Sra. da Conceição",
  "Vila N. Sra. das Graças",
  "Vila N. Sra. de Lourdes",
  "Vila Nascente",
  "Vila Nasser",
  "Vila Neuza",
  "Vila Nilza",
  "Vila Nogueira",
  "Vila Nova",
  "Vila Nova Bandeirantes",
  "Vila Nova São Bento",
  "Vila Novo Horizonte",
  "Vila Olga",
  "Vila Olinda",
  "Vila Oliveira",
  "Vila Onze",
  "Vila Oracília",
  "Vila Oriente",
  "Vila Ornelas",
  "Vila Orpheu Baís",
  "Vila Orsi",
  "Vila Ouro Fino",
  "Vila Palmira",
  "Vila Paraíso",
  "Vila Paulistana",
  "Vila Perseverança",
  "Vila Piratininga",
  "Vila Planalto",
  "Vila Portão de Ferro",
  "Vila Progresso",
  "Vila Quito",
  "Vila Raquel",
  "Vila Ravenna",
  "Vila Rezende",
  "Vila Rica",
  "Vila Rolim",
  "Vila Romana",
  "Vila Rosa",
  "Vila Rosa Pires",
  "Vila Sant'ana",
  "Vila Santa Barbara",
  "Vila Santa Branca",
  "Vila Santa Dorothea",
  "Vila Santa Filomena",
  "Vila Santa Luiza",
  "Vila Santa Luzia",
  "Vila Santa Maria",
  "Vila Santa Odete",
  "Vila Santa Rita",
  "Vila Santa Rosa",
  "Vila Santa Tereza",
  "Vila Santério",
  "Vila Santo Amaro",
  "Vila Santo André",
  "Vila Santo Antonio",
  "Vila Santo Eugênio",
  "Vila Santos",
  "Vila Santos Gomes",
  "Vila São Elias",
  "Vila São Francisco",
  "Vila São Gabriel",
  "Vila São João",
  "Vila São João Bosco",
  "Vila São Jorge",
  "Vila São Jorge da Lagoa",
  "Vila São José",
  "Vila São Luís",
  "Vila São Miguel",
  "Vila São Rapael",
  "Vila São Sebastião",
  "Vila São Thomé",
  "Vila São Vicente",
  "Vila Saraiva",
  "Vila Sargento Amaral",
  "Vila Serradinho",
  "Vila Sílvia",
  "Vila Sílvia Regina",
  "Vila Soares",
  "Vila Sobrinho",
  "Vila Sol Nascente",
  "Vila Sônia",
  "Vila Suburbano",
  "Vila Suíça",
  "Vila Taquari",
  "Vila Taquarussú",
  "Vila Taveira",
  "Vila Taveirópolis",
  "Vila Telma",
  "Vila Tupaceretan",
  "Vila Valparaíso",
  "Vila Vilas Boas",
  "Vila Vilma",
  "Vila Volpe",
  "Vila Volpe II",
  "Vila Warde",
  "Vila XV de Novembro",
  "Vila Zoe",
  "Villa Di Parma",
  "Villa Ravena",
  "Villagio Riviera",
  "Villas Park Residence",
  "Vivendas do Bosque",
  "Vivendas do Parque",
  "Zona Rural"
];

const Input = ({ attribute, disabled, intlLabel, name, onChange, required, value }: InputProps) => {
  const { formatMessage } = useIntl();
  const label =
    intlLabel && intlLabel.id
      ? formatMessage(intlLabel)
      : (intlLabel as any)?.defaultMessage || 'Bairro';
  
  // Value handling for compatibility: {regiao, bairro} or string
  const currentBairro = value && typeof value === 'object' 
    ? value.bairro 
    : (typeof value === 'string' ? value : '');

  const handleBairroChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const bairro = event.target.value;
    // We keep sending the object structure to maintain backend compatibility if needed,
    // but regiao is now always empty.
    onChange({
      target: {
        name,
        type: attribute.type,
        value: { regiao: '', bairro },
      },
    });
  };

  return (
    <div style={{ display: 'grid', gap: '8px' }}>
      <label style={{ fontWeight: 600, fontSize: '0.75rem', color: '#4b5563' }}>{label}</label>
      <select
        name={name}
        value={currentBairro}
        onChange={handleBairroChange}
        disabled={disabled}
        required={required}
        style={{ 
          width: '100%', 
          padding: '8px 12px', 
          borderRadius: '4px', 
          border: '1px solid #d1d5db',
          backgroundColor: disabled ? '#f3f4f6' : 'white'
        }}
      >
        <option value="">Selecione o bairro</option>
        {todosBairros.map((bairro) => (
          <option key={bairro} value={bairro}>
            {bairro}
          </option>
        ))}
      </select>
    </div>
  );
};

Input.displayName = 'BairroRegiaoInput';

export default Input;
