/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    bairros: Bairro;
    imoveis: Imovei;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bairros: BairrosSelect<false> | BairrosSelect<true>;
    imoveis: ImoveisSelect<false> | ImoveisSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  cloudinaryUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bairros".
 */
export interface Bairro {
  id: number;
  /**
   * Ex: Centro, Jardim dos Estados, Nova Lima
   */
  nome: string;
  /**
   * Gerado automaticamente
   */
  slug: string;
  regiao: 'centro' | 'norte' | 'sul' | 'leste' | 'oeste' | 'anhanduizinho' | 'bandeira';
  /**
   * Informações sobre o bairro, pontos de interesse, etc.
   */
  descricao?: string | null;
  /**
   * Mostrar este bairro em destaque no site
   */
  destaque?: boolean | null;
  /**
   * Foto representativa do bairro (opcional)
   */
  imagem?: (number | null) | Media;
  /**
   * Centro geográfico do bairro
   */
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Menor número aparece primeiro
   */
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imoveis".
 */
export interface Imovei {
  id: number;
  /**
   * Ex: Casa com 3 quartos no Centro
   */
  titulo: string;
  /**
   * Gerado automaticamente a partir do título
   */
  slug: string;
  tipo: 'casa' | 'apartamento' | 'kitnet' | 'sobrado' | 'cobertura' | 'terreno' | 'comercial' | 'galpao' | 'chacara';
  finalidade: 'aluguel' | 'venda' | 'ambos';
  status: 'disponivel' | 'alugado' | 'vendido' | 'indisponivel' | 'rascunho';
  /**
   * Descreva os principais atrativos do imóvel
   */
  descricao: string;
  /**
   * Valor do aluguel ou venda
   */
  preco: number;
  /**
   * Deixe vazio se não houver
   */
  condominio?: number | null;
  /**
   * Valor mensal aproximado
   */
  iptu?: number | null;
  quartos?: number | null;
  suites?: number | null;
  banheiros?: number | null;
  vagas?: number | null;
  area?: number | null;
  areaConstruida?: number | null;
  /**
   * Selecione todas que se aplicam
   */
  caracteristicas?:
    | (
        | 'mobiliado'
        | 'semi-mobiliado'
        | 'ar-condicionado'
        | 'piscina'
        | 'churrasqueira'
        | 'quintal'
        | 'varanda'
        | 'sacada'
        | 'elevador'
        | 'portaria'
        | 'academia'
        | 'salao-festas'
        | 'playground'
        | 'pet-friendly'
        | 'financiamento'
      )[]
    | null;
  /**
   * Rua, número (opcional por privacidade)
   */
  endereco?: string | null;
  /**
   * Selecione o bairro
   */
  bairro: number | Bairro;
  cep?: string | null;
  /**
   * Para mapa (opcional)
   */
  latitude?: number | null;
  /**
   * Para mapa (opcional)
   */
  longitude?: number | null;
  /**
   * Adicione fotos do imóvel (primeira será a capa)
   */
  fotos: {
    imagem: number | Media;
    /**
     * Ex: Sala de estar, Cozinha, Quarto principal
     */
    legenda?: string | null;
    destaque?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Deixe vazio para usar o padrão
   */
  corretor?: string | null;
  /**
   * Ex: (67) 99999-9999
   */
  telefone?: string | null;
  email?: string | null;
  /**
   * Título para Google (deixe vazio para usar o título)
   */
  metaTitle?: string | null;
  /**
   * Descrição para Google (156 caracteres)
   */
  metaDescription?: string | null;
  /**
   * Mostrar este imóvel em destaque
   */
  destaque?: boolean | null;
  /**
   * Contador automático de visualizações
   */
  visualizacoes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'bairros';
        value: number | Bairro;
      } | null)
    | ({
        relationTo: 'imoveis';
        value: number | Imovei;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bairros_select".
 */
export interface BairrosSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  regiao?: T;
  descricao?: T;
  destaque?: T;
  imagem?: T;
  latitude?: T;
  longitude?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imoveis_select".
 */
export interface ImoveisSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  tipo?: T;
  finalidade?: T;
  status?: T;
  descricao?: T;
  preco?: T;
  condominio?: T;
  iptu?: T;
  quartos?: T;
  suites?: T;
  banheiros?: T;
  vagas?: T;
  area?: T;
  areaConstruida?: T;
  caracteristicas?: T;
  endereco?: T;
  bairro?: T;
  cep?: T;
  latitude?: T;
  longitude?: T;
  fotos?:
    | T
    | {
        imagem?: T;
        legenda?: T;
        destaque?: T;
        id?: T;
      };
  corretor?: T;
  telefone?: T;
  email?: T;
  metaTitle?: T;
  metaDescription?: T;
  destaque?: T;
  visualizacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}